DROP TABLE IF EXISTS public."PA_Data";
CREATE TABLE public."PA_Data"
(
	"Country" text,
	"PEPFAR" text,
	"Signed" text,
	"Deposited" text,
	"SignedDeposited" text,
	"Maternity_Health_Access_to_Care" text,
	"Human_Trafficking" text,
	"ICAO" text,
	"UNESCO" text,
	"FAO" text,
	"OAS" text,
	"UNGA" text,
	"OSCE" text,
	"OECD" text,
	"NATO" text,
	"EU" text,
	"AU" text,
	"UNHCR" text,
	"MLO_Index" real,
	"APEC" text,
	"NAFTA" text,
	"WTO" text,
	"ASEAN" text,
	"CBERA" text,
	"CAFTA" text,
	"TP_Index" real,
	"Global_Health" real,
	"DHRA" real,
	"Wat_San" real,
	"Crisis_Conflict" real,
	"Gender_Women" real,
	"Env_Climate" real,
	"Science" real,
	"NIV_1997" real,
	"NIV_1998" real,
	"NIV_1999" real,
	"NIV_2000" real,
	"NIV_2001" real,
	"NIV_2002" real,
	"NIV_2003" real,
	"NIV_2004" real,
	"NIV_2005" real,
	"NIV_2006" real,
	"NIV_2007" real,
	"NIV_2008" real,
	"NIV_2009" real,
	"NIV_2010" real,
	"NIV_2011" real,
	"NIV_2012" real,
	"NIV_2013" real
);

set client_encoding to 'UTF-8';

COPY "PA_Data" FROM 'C:\OpenGeo\webapps\DiplomacyExplorer2\sql\PA_Data.csv' DELIMITER ',' CSV;